"""Add deleted timestamps for trash

Revision ID: 66098da10c05
Revises: 3adde198d376
Create Date: 2026-09-03 10:53:56.700865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66098da10c05'
down_revision: Union[str, Sequence[str], None] = '3adde198d376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_files_deleted_at'), 'files', ['deleted_at'], unique=False)
    op.add_column('folders', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_folders_deleted_at'), 'folders', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_deleted_at'), table_name='folders')
    op.drop_column('folders', 'deleted_at')
    op.drop_index(op.f('ix_files_deleted_at'), table_name='files')
    op.drop_column('files', 'deleted_at')
    # ### end Alembic commands ###
