"""Add soft delete to folders

Revision ID: 9642352cab9f
Revises: b98ffa4bb8dd
Create Date: 2026-08-31 18:48:08.359396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9642352cab9f'
down_revision: Union[str, Sequence[str], None] = 'b98ffa4bb8dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_folders_is_deleted'), 'folders', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_folders_is_deleted'), table_name='folders')
    op.drop_column('folders', 'is_deleted')
    # ### end Alembic commands ###
