"""Updated in file relationship

Revision ID: d366a7077faf
Revises: 0495d0257b86
Create Date: 2026-08-28 18:53:03.355300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd366a7077faf'
down_revision: Union[str, Sequence[str], None] = '0495d0257b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'shared_with_user_id', name='uq_file_shared_user')
    )
    op.create_index(op.f('ix_shares_file_id'), 'shares', ['file_id'], unique=False)
    op.create_index(op.f('ix_shares_shared_with_user_id'), 'shares', ['shared_with_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shares_shared_with_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_file_id'), table_name='shares')
    op.drop_table('shares')
    # ### end Alembic commands ###
