"""Add folder sharing support

Revision ID: db7812dd3125
Revises: d366a7077faf
Create Date: 2026-08-28 19:58:23.724062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db7812dd3125'
down_revision: Union[str, Sequence[str], None] = 'd366a7077faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shares', sa.Column('folder_id', sa.UUID(), nullable=True))
    op.alter_column('shares', 'file_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_shares_folder_id'), 'shares', ['folder_id'], unique=False)
    op.create_unique_constraint('uq_folder_shared_user', 'shares', ['folder_id', 'shared_with_user_id'])
    op.create_foreign_key(None, 'shares', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='foreignkey')
    op.drop_constraint('uq_folder_shared_user', 'shares', type_='unique')
    op.drop_index(op.f('ix_shares_folder_id'), table_name='shares')
    op.alter_column('shares', 'file_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('shares', 'folder_id')
    # ### end Alembic commands ###
