"""Add public share links

Revision ID: ecd8cd11867a
Revises: db7812dd3125
Create Date: 2026-08-30 18:02:54.013473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecd8cd11867a'
down_revision: Union[str, Sequence[str], None] = 'db7812dd3125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_links_file_id'), 'public_links', ['file_id'], unique=False)
    op.create_index(op.f('ix_public_links_folder_id'), 'public_links', ['folder_id'], unique=False)
    op.create_index(op.f('ix_public_links_token'), 'public_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_links_token'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_folder_id'), table_name='public_links')
    op.drop_index(op.f('ix_public_links_file_id'), table_name='public_links')
    op.drop_table('public_links')
    # ### end Alembic commands ###
