"""add new field in user model

Revision ID: f09c3e6892ff
Revises: ffc622cd0bb9
Create Date: 2026-09-07 18:57:54.911795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09c3e6892ff'
down_revision: Union[str, Sequence[str], None] = 'ffc622cd0bb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('storage_limit', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('storage_used', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_used')
    op.drop_column('users', 'storage_limit')
    # ### end Alembic commands ###
