"""add public link permission

Revision ID: ffc622cd0bb9
Revises: 66098da10c05
Create Date: 2026-09-04 18:29:07.799961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffc622cd0bb9'
down_revision: Union[str, Sequence[str], None] = '66098da10c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    "public_links",
    sa.Column(
        "permission",
        sa.String(length=20),
        nullable=False,
        server_default="viewer",
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('public_links', 'permission')
    # ### end Alembic commands ###
